name: Java CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java 1.8
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    # Step 3: Compile the project using Maven
    - name: Compile the project using Maven
      run: mvn clean compile

    # Step 4: Run the Java application
    - name: Run the Java application
      run: java -cp target/classes com.example.HelloWorld
